sudo: required
services:
  - docker

before_install:
  - docker build -t sjegadison/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sjegadison/react-test npm test

# after_success:
  - docker build -t sjegadison/multi-client ./client
  - docker build -t sjegadison/multi-nginx ./nginx
  - docker build -t sjegadison/multi-server ./server
  - docker build -t sjegadison/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sjegadison/multi-client
  - docker push sjegadison/multi-nginx
  - docker push sjegadison/multi-server
  - docker push sjegadison/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app:  "docker-multi"
  env:  "DockerMulti-env"
  bucket-name:  "elasticbeanstalk-ap-south-1-748645781037"
  bucket-path:  "docker-multi"
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  on:
    branch: master
